Fixed layout
Team-Zoldyck/P2MAX pull request #20
Opened 2022-06-04 22:12 UTC by ImieboGodson

- Added Wrapper component that holds header and footer then loads routes dynamically

2022-06-05 14:49 UTC, MorganJay requested changes

2022-06-05 14:49 UTC, MorganJay commented on frontend/src/utils/Wrapper.jsx
> +const Wrapper = () => {
I don't know if this Wrapper needs to be extracted into its own component, this adds more complexity. you can just import the Navbar and Footer in the App component

2022-06-05 14:49 UTC, MorganJay commented on frontend/src/utils/Wrapper.jsx
> +const Wrapper = () => {
Then again the Navbar and Footer are rendered conditionally across some other screens of the whole web app, so you might want to prepare for that now

2022-06-05 17:48 UTC, ImieboGodson commented
@MorganJay  see current  change according to your last review

2022-06-05 20:43 UTC, MorganJay requested changes

2022-06-05 20:43 UTC, MorganJay commented on frontend/src/App.js
> +        (route === '' || route === 'FAQs' || route === 'aboutUs' || route === 'support')
a switch statement would look cleaner and more readable here

2022-06-06 09:54 UTC, ImieboGodson commented
@MorganJay Kindly find changes as requested.

2022-06-06 15:56 UTC, merged